name: CI-CD
env:
  EB_PACKAGE_S3_BUCKET_NAME: "cicd-github-actions"
  EB_APPLICATION_NAME: "GitHubActions"
  EB_ENVIRONMENT_NAME: "GitHubActions-env"
  DEPLOY_PACKAGE_NAME: "ci-cd-app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1"

on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
        
      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

